### ISSUE TITLE
Pod support?

### ISSUE THREAD

**Issue by Stefanhym** [rizumita/CTFeedbackSwift#1]
Hi, great work?
Any plan to support pod in the near future?

**Comment by rizumita** [comment]
@Stefanhym Yes, I will make CTFeedbackSwift supports CocoaPods.

**Comment by rizumita** [comment]
@Stefanhym 
CTFeedbackSwift supported CocoaPods with fixing bugs.
Please try using CTFeedbackSwift installing by CocoaPods.

**Comment by Stefanhym** [comment]
Great! Thanks!
