### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by furiosFast** [rizumita/CTFeedbackSwift#16]
Hi,
can you add support for swift package manager?

thank

**Comment by rizumita** [comment]
@furiosFast I'll try supporting SPM.

**Comment by furiosFast** [comment]
An example:

```
import PackageDescription

let package = Package(
    name: "CTFeedbackSwift",
    platforms: [
        // Some platform where run yours library
        .iOS(.v11), .tvOS(.v11), .watchOS(.v4)
    ],
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(name: "CTFeedbackSwift", targets: ["CTFeedbackSwift"]),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(name: "CTFeedbackSwift"),
    ],
    swiftLanguageVersions: [
        .v5
    ]
)
```

**Comment by rizumita** [comment]
@furiosFast 
CTFeedbackSwift has bundle resources. So I think CTFeedbackSwift can't support SPM.

**Comment by Hengyu** [comment]
@rizumita 
Speaking of bundle resources, do you mean the localized string files or the plist file?

**Comment by rizumita** [comment]
@Hengyu Yes. And thank you for your PR.

**Comment by Hengyu** [comment]
Yeah, I have noticed that. However, this repo is still able to support for SPM. 
And as a workaround to take care of the localizing issue, we can use the solution from this repo: https://github.com/carekit-apple/CareKit .

> To add localized strings to your project, add the strings file to your project: English Strings

We can explicity add localizable resources into our project.
