### ISSUE TITLE
Feedback Generation Error when "hidesAppInfoSection: true"

### ISSUE THREAD

**Issue by numen31337** [rizumita/CTFeedbackSwift#2]
If you set`hidesAppInfoSection: true` like so:
```swift
let configuration = FeedbackConfiguration(toRecipients: ["ios.apps.maintenance@gmail.com"], hidesAppInfoSection: true, usesHTML: true)
```
You have Feedback Generation Error when pressing the Send button.

**Comment by rizumita** [comment]
@numen31337 I fixed the bug. Thank you!

**Comment by numen31337** [comment]
With this issue being fixed, now when users send feedback, it still contains app info section, but its empty like so:
* Device: iPad7,3
* iOS: 11.4
* App: 
* Version: 
* Build:
