### ISSUE TITLE
Enabling/disabling photo attachment

### ISSUE THREAD

**Issue by furiosFast** [rizumita/CTFeedbackSwift#27]
Hello,
it would be possible to add the possibility of enabling/disabling the possibility of attaching images (from roll or camera) to the feedback email

**Comment by rizumita** [comment]
@furiosFast 
You can do that by using this configuration.
https://github.com/rizumita/CTFeedbackSwift/blob/5914e16f73e57a2de21c305dce1b8bd821672ba3/CTFeedbackSwift/FeedbackConfiguration.swift#L27

**Comment by furiosFast** [comment]
ok, nice!
thank yuo!

Can you create a new tag of the project for download the new versione with SPM?

**Comment by furiosFast** [comment]
ok, thank you.
Can you create a new tag of the project for SPM with the new chages?
