### ISSUE TITLE
iPhone X, Xr and max

### ISSUE THREAD

**Issue by mriccasyncpoint** [rizumita/CTFeedbackSwift#6]
Hi,
can you add support for new iOS device?

**Comment by rizumita** [comment]
@mriccasyncpoint Yes, I'm going to work.

**Comment by furiosFast** [comment]
are these the new iPhone code?
iPhoneXS: iPhone11,2
iPhoneXSMax: iPhone11,4 and iPhone11,6
iPhoneXR: iPhone11,8

**Comment by rizumita** [comment]
I pushed version 0.1.6 supported new iOS devices.
