### ISSUE TITLE
CTFeedbackSwift support swift 4.2 

### ISSUE THREAD

**Issue by kristoff2016** [rizumita/CTFeedbackSwift#7]
Hello, thank you for your lib but really need support swift 4.2 

thank you

**Comment by rizumita** [comment]
@kristoff2016 I'll work. Perhaps tomorrow.

**Comment by kristoff2016** [comment]
@rizumita thank you so much

**Comment by rizumita** [comment]
@kristoff2016 
I checked whether the CTFeedbackSwift supports Swift 4.2, and the latest version supports Swift 4.2.
Please recheck it.

**Comment by kristoff2016** [comment]
thank you so much
